services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FriendsOfTYPO3\HeadlessSocialFeed\:
    resource: '../Classes/*'

  FriendsOfTYPO3\HeadlessSocialFeed\Command\ImportFeedsCommand:
    tags:
      - name: console.command
        command: 'headlesssocialfeed:importfeeds'
        description: 'Import feeds from default facebook configuration'
        schedulable: true
